### ISSUE TITLE
How do I get url from element data using element API?

### ISSUE THREAD

**Issue by toddpadwick** [sebastian-lenz/craft-linkfield#116]
I am using element API to create a json endpoint which I will use to render content in vue js. 
However, I can't see how to get the link field url. it seems to output everything else but not the actual url?

This is what is outputted in the json file.

Im relatively new to using craft headlessly so forgive me if this is a silly question.

```
buttons: [
    {
        link: {
            ariaLabel: null,
            customQuery: null,
            customText: "Enquire",
            target: "",
            title: null,
            type: "entry",
            value: "2204"
        }
    }
]
```

**Comment by sebastian-lenz** [comment]
Hi @toddpadwick, it looks like the Element API plugin simply exports the members that are present on the value model of the link. What you see right here are the basic values as we store them to the database, the attribute `value` contains the id of the linked entry. In order to resolve the actual url, the link field plugin loads this entry and returns the url.

We currently do not have a dedicated support for the Element API plugin, but it I think it would be a great addition to the link field plugin. Currently the plugin supports GraphQL (v1 supports the deprecated third party plugin, v2 supports the Craft CMS GraphQL). I'll mark this issue as a feature request.

Looking at the data structure I guess you are using v1 of the link field. If we enhance the Element API support, we will definitely include it in the v2 branch of the plugin.

**Comment by toddpadwick** [comment]
Excellent, thank you!

I probably should start using Graph QL. I tried but i struggled as its a
lot more advanced than element API.

**Comment by sebastian-lenz** [comment]
I've looked into the ElementAPI source code and as it turns out the plugin does not offer any hooks or events we could use to change the returned data, the ElementAPI will always just return the serialized values of the field: 
https://github.com/craftcms/element-api/blob/v2/src/ElementTransformer.php#L20
