### ISSUE TITLE
Add URI link format for GraphQL

### ISSUE THREAD

**Issue by saltymouse** [sebastian-lenz/craft-linkfield#123]
When using Craft with Vue in headless mode, the `<router-link to="...">` just needs a URI (path segment after the domain) rather than the full URL (scheme + domain + path). I'd be a nice touch to query this directly from GraphQL rather than processing the URL into a URI.

Example of URL and URI in query:
```graphql
query {
  button {
    ariaLabel
    customText
    target
    text
    title
    type
    url
    uri
  }
}
```
Example response:
```graphql
{
  "button": {
    "ariaLabel": null,
    "customText": null,
    "target": null,
    "text": "Events List",
    "title": null,
    "type": "entry",
    "url": "https://localhost:8080/events/2020",
    "uri": "events/2020"
  }
}
```

Great plugin!

**Comment by sebastian-lenz** [comment]
Hi @saltymouse, thanks for your suggestion. We expose the linked element via the `element` field, so maybe you can fetch the desired info via `element.slug`?

**Comment by toddpadwick** [comment]
Exposing the `element` is great - this surely closes this ticket as thats a complete solution. You can even get element.uri if needed.

**Comment by saltymouse** [comment]
Indeed, I ended up using the `element.slug` field to fetch the slug for my button (solving my initial problem). Thanks!

**Comment by ajoliveau** [comment]
I'll reopen this !
I have this need on a Nuxt website and it's the same problem, the built-in <NuxtLink> component needs a uri for internal links.

But my website is multisite, so fetching the `element.slug` doesn't give me all the information because all my urls have the language at the root, like https://www.example.com/fr/contact and https://www.example.com/en/contact. `element.slug` gives me `contact` in both cases where what I would love is `/fr/contact`.

The best way to do it would be to return a `uri` graphql field that is like `url` with the current site domain removed.

Does this featured make sense ?

**Comment by ajoliveau** [comment]
I'm going to open a new issue if that's ok

**Comment by sebastian-lenz** [comment]
Please do not open an issue for feature requests, start a discussion instead. Also I don't see any need to change something here, if you don't like to wirk with absolute urls just update your site settings to return relative urls. The "issue" is not related to the link field, all urls generated by Craft will be absolute in your use case.
