### ISSUE TITLE
GraphQL query

### ISSUE THREAD

**Issue by clieee** [sebastian-lenz/craft-linkfield#139]
Is it possible to query the field via GraphQL? All I get from the explorer menu is the handle name, and the value I have entered. How can I get the values such as aria label etc?

**Comment by sidm1983** [comment]
@clieee I am also having trouble with this. Looks like only the URL can be retrieved via GraphQL.

I am unable to retrieve the other fields like the link type, custom link text, aria label or the "Open in new window?" checkbox fields. Would also be good to be able to retrieve details about the selected element for "Entry", "Asset" and "Category" types.

@sebastian-lenz would it be possible to add GraphQL support to this plugin? 🙏🏽🙌🏽

**Comment by sebastian-lenz** [comment]
Hi @clieee, Hi @sidm1983, we have support for the third-party GraphQL plugin in the v1 version of the plugin and the native GraphQL mode is supported in v2. In both instances all properties of the link are exposed but we do not offer any query mechanisms.

I guess you are both using version 1, which is the version that can be found in the plugin store? To upgrade to the new version you would have to adjust your composer file to point to the new release channel with something like this:
```
{
  "require": {
    "sebastianlenz/linkfield": "^2.0.0-beta.12"
  }
}
```

Please create a database backup before upgrading as the new version comes with a new table structure. If you run into any issues while upgrading, please report them here.

**Comment by sidm1983** [comment]
@sebastian-lenz thank you for letting us know about this. Glad to see there is a solution. Do you have a rough ETA on when version 2.0.0 will be officially release to the plugin store? I can definitely test the beta version locally, but would prefer to use a stable version for production eventually. Please let me know when you get a chance. Thank you.

**Comment by sidm1983** [comment]
@sebastian-lenz I have just tested version 2.0.0-beta.12 locally and my graphQL queries are working now and I am getting back the data as expected.

There is one small issue though. The Graph(i)QL explorer doesn't seem to be displaying the field under the entry type I have added the Link Field to. Graph(i)QL is showing a red squiggly line underneath that field in my query (suggesting that no such field exists), but the query itself executes just fine and returns the expected results.

Is there something missing in the configuration of the field class that is preventing it from correctly registering itself with the native GraphQL module?

If I add the Link Field to a Super Table column, then it shows up correctly in Graph(i)QL. I am not sure what is going on here. Any thoughts on this?

Thank you.

**Comment by sidm1983** [comment]
@sebastian-lenz actually don't worry about my previous comment about the field not showing up in Graph(i)QL. I think that was happening because I had first installed version 1 of the plugin from the plugin store which corrupted my database. I was able to recreate my local dev environment (thanks to docker) and everything seems to be working well now.

I would still like to know if there is an ETA for when version 2.0.0 will be release officially to the plugin store. Also, if I do end up using the beta even for production, when the stable version 2.0.0 gets released, will Craft CMS auto-detect that there is an update and let me update without needing to uninstall the beta version and without losing any data in the link field across the entries in the CMS?

Please let me know when you get a chance. Thank you!

**Comment by sebastian-lenz** [comment]
@sidm1983 Version 2 of the plugin ist still in beta as the uphrade process is still a bit rocky. If you start a new project or if the upgrade works fine for you I would use v2.
