### ISSUE TITLE
Column not found error on creating link field in a matrix

### ISSUE THREAD

**Issue by robmcfadden** [sebastian-lenz/craft-linkfield#163]
I'm unable to create a matrix with a link field in one of its blocks. Getting a "Column not found" error related to the first field I have, alphabetically. So in my case, the specific error is: `Column not found: 1054 Unknown column 'content.field_primaryItem_altText' in 'field list'`

Any help here is appreciated!

PHP version | 7.4.16
Database driver & version | MySQL 8.0.21
Craft edition & version | Craft Pro 3.7.7
Typed link field | 2.0.0-rc.1

**Comment by daltonrooney** [comment]
I just came to report a similar issue. I'm trying to edit an existing matrix on a site that was recently upgraded from Craft 3.5.x to 3.7.x. Whenever I try to save a change to the matrix, I get a `Database Exception`

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_button_aboutHost' in 'field list'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `elements`.`canonicalId`, `elements`.`dateLastMerged`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_button_aboutHost`, `content`.`field_button_address_kmrgzszn`, `content`.`field_button_altText`, `content`.`field_button_notificationBody`, `content`.`field_button_caption`, `content`.`field_button_cost`, `content`.`field_button_endDateTime`, `content`.`field_button_externalLink`, `content`.`field_button_featured`, `content`.`field_button_format`, `content`.`field_button_homepageIntro_zoryqqsc`, `content`.`field_button_introContent`, `content`.`field_button_introHeading`, `content`.`field_button_pageIntro`, `content`.`field_button_pageIntroRichText_wlchdvla`, `content`.`field_button_partnerDescription`, `content`.`field_button_partnerLabel`, `content`.`field_button_primaryDescription`, `content`.`field_button_primaryDescriptionEs`, `content`.`field_button_seoTitle`, `content`.`field_button_shortDescription`, `content`.`field_button_source`, `content`.`field_button_sponsorDescription`, `content`.`field_button_startDateTime`, `content`.`field_button_supportOurWorkDescription_bnkxqqsc`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
...
```
I've never had a field called `button_aboutHost` or `button_address_kmrgzszn`... I _do_ have a block called `button` in the matrix which includes a link field called `button, however.

@robmcfadden Do you have a link field somewhere in your matrix called `primaryItem`?

**Comment by kylecotter** [comment]
Can confirm this happens on a fresh install as well when adding a Link field inside a Matrix block. Was able to reproduce with any naming combo. Thanks!

**Comment by sebastian-lenz** [comment]
I've just done a quick test in my local Craft 3.7.7 test installation: I've created a new Matrix field containing different blocks both with and without a link field. My quick tests a working fine, I don't see no errors and the fields / matrices work like expected. So there must be something more to the issue here.

It's pretty strange that there are SQL errors because the link field does not have a column within the content table. Additionally, the column names in the error message (like `field_primaryItem_altText` or `field_button_aboutHost`) won't exist like that in Craft 3.7.7 as Craft now appends a unique id to the column names.

So are there any other plugins at play here? And did the migrations after the Craft upgrade run correctly?

**Comment by kylecotter** [comment]
Hi @sebastian-lenz,

I debugged this a bit more and found a reproducible case with the Expanded Singles plugin in use which I mistakenly forgot was in my test setup earlier:

1. Have a Matrix field with a Link field setup inside a block type
2. Have at least one other field exist on the site
3. Have at least one Single section setup
4. Have Verbb’s Expanded Singles plugin installed - https://github.com/verbb/expanded-singles


Now if you go into your Matrix -> Link field setup, under the Entry section of the Link field settings, ensure all the entry sources are checked (which happens by default), and try to save the update to the matrix field.

A DB error occurs.

This only happens if a single exists, if another field exists aside from the matrix field, if the entry sources section of the link fieltype settings are checked off, and if the Expanded Singles plugin is enabled.

So, definitely a pretty specific set of circumstances.

Hope that helps. Not sure if this bug still falls under the Link fieldtype or Expanded Entries.

Thanks!

**Comment by kylecotter** [comment]
Hey @sebastian-lenz, have you had any time to circle back to this? Totally understand everyone is busy!

I'm still trying to nail down the root cause of this, maybe @engram-design has an idea from the expanded singles side.

Thanks, all!

**Comment by brandonkelly** [comment]
Just fixed this for the next Craft release – see https://github.com/craftcms/cms/issues/9749#issuecomment-904974037.
