### ISSUE TITLE
Entries From Other Sites Not Available as Options, Even When Allowed in Field Settings

### ISSUE THREAD

**Issue by itsmattsoria** [sebastian-lenz/craft-linkfield#169]
I've got a multi-site setup going where the different sites aren't different translations, they're actually separate sites, but I want to allow the client to link to entries from other sites. For the Link Field in question, I've clicked on "Entry" to edit the settings there and all of the entries from the other sites I want available as options are enabled:

![Screen-Shot-2021-09-02-07-11-26](https://user-images.githubusercontent.com/2831517/131841398-460487a3-f497-4c72-a182-d4168b2f3168.jpg)

But then when I go to edit that field from the entry it appears in and then click on "choose", only the entries for the current site's (the site that I'm editing the entry in) entries are available to choose from:

![Screen-Shot-2021-09-02-07-13-36](https://user-images.githubusercontent.com/2831517/131841731-ce73ca4d-40a8-4bc8-8fbe-17895910e744.jpg)

I'm not sure if this is a limitation on the Craft side of things but wondered if there was a way to get around this and allow all entries across sites (or at least all entries enabled in the field settings) to be choosable. 

Thanks for such a handy plugin by the way!

**Comment by nicgoodman-em** [comment]
I'm having the exact same issue. I was going to update to 2.0.0 RC1 but it looks like Craft 3.7 breaks the release candidate. Any suggestions for how to get around this besides just manually typing in a direct link to the entry? Otherwise, this is a fantastic plugin, I really hope it doesn't get/is abandoned!

**Comment by luke-nehemedia** [comment]
I would also very like to have the option to select fields from different sites.

**Comment by sebastian-lenz** [comment]
The feature to select links from other sites is available in version 2 of the plugin.

**Comment by jannisborgers** [comment]
Hey @sebastian-lenz — any chance selecting entries from other sites will be available for Craft 3? 😬 We can’t upgrade the site to Craft 4 unfortunately because of another integral plugin. I already pushed for a Craft 4 upgrade there, but hoped it might be possible to get Link Field functionality in Craft 3 as an alternative.

**Comment by sebastian-lenz** [comment]
@jannisborgers Sorry, I don't have the time to port the feature back to the old version. If you would like to add it, I would happily accept any pull requests.

**Comment by jannisborgers** [comment]
> @jannisborgers Sorry, I don't have the time to port the feature back to the old version. If you would like to add it, I would happily accept any pull requests.

Understandably so, Sebastian. Was worth a try. I’d rather upgrade the site to Craft 4 as well.
