### ISSUE TITLE
Entry selection doesnt work

### ISSUE THREAD

**Issue by piotrpog** [sebastian-lenz/craft-linkfield#50]
I have matrix field, each block has link field with entry and category selection allowed.
When i want to select entry, window apperars, but it just shows preloader. When i close window and click it second time, it wont appear at all.
Category selection window works ok.

These is browser console error that appears after first click (i have devmode enabled):
```
jquery.js:9566 POST http://address/web/index.php?p=admin/actions/elements/get-modal-body 500 (Internal Server Error)
```
This is error that appears after second click:
```
Craft.js:4281 Uncaught TypeError: Cannot read property 'getSelectedElements' of null
    at s.constructor.updateSelectBtnState (Craft.js:4281)
    at s.constructor.show (Craft.js:4354)
    at s.constructor.e [as show] (garnish.js:79)
    at s.constructor.showModal (Craft.js:4053)
    at s.constructor.i (jquery.js:496)
    at s.constructor.<anonymous> (garnish.js:893)
    at HTMLDivElement.i (jquery.js:496)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.v.handle (jquery.js:5014)
    at Object.trigger (jquery.js:8201)
```

I have similar versions of this field in matrix in other parts of page and they work OK.

This probably appeared after updating to craft 3.1. My current version is Craft CMS `3.1.5` and typed link field version is `1.0.16`.

**Comment by superflausch** [comment]
I have the same or a similar issue since updating to Craft 3.1.x. My field isn't nested in a matrix field and the error I'm getting is another one. Same behaviour, trying to select an entry, modal opens, is stuck with the spinner and throws an error message. The error I'm getting is:

´{"error":"Argument 2 passed to craft\\helpers\\ElementHelper::findSource() must be of the type string, array given, called in /mypath/vendor/craftcms/cms/src/controllers/ElementsController.php on line 57"}´

Latest versions I tested are CraftCMS 3.1.7 and the plugin on 1.0.16.

**Comment by superflausch** [comment]
The request is sent to ```/index.php/admin/actions/elements/get-modal-body```, resulting in an error 500 containing the message mentioned before.

What additional info would help? The issues occurs since the update to Craft 3.1. I have the same issue on our PROD (PHP 7.2.13) and my local DEV (PHP 7.2.11) environment. It's a simple link field assigned to the only entry type within a channel. No multisite setup. Couple of other plugins.

Cheers.

**Comment by sebastian-lenz** [comment]
With the Craft 3.1 update the core has changed the way sections are referenced, we had an issue (#49) that covered this and I thought we resolved the issue. I guess in your cases the fix is not applied correctly so it would be interesting to find out why. The ajax request sends some additional data which can be observed in the develop tools form data section:

![bildschirmfoto 2019-02-05 um 12 27 34](https://user-images.githubusercontent.com/2273359/52270551-a1762b80-2941-11e9-973f-ab021eaf9799.png)

I guess in your case the `sources` array is not configured correctly. You should easily be able to resolve this issue by resaving the field settings. But it would be great if you could share the sent payload for further investigation.

**Comment by superflausch** [comment]
Resaving indeed resolved the issue for us. Thank you.

Sure thing. Here is the data of the request resulting in the error:

![screenshot 2019-02-05 at 13 35 48](https://user-images.githubusercontent.com/539103/52273936-8d372c00-294b-11e9-9362-b725212394d1.png)

**Comment by sebastian-lenz** [comment]
Ah, okay, some internal stuff gets sent there, I've created a patch. Thanks for sharing!

**Comment by piotrpog** [comment]
If it helps, there is my form data that is sent:

context: modal
elementType: craft\elements\Entry
sources[0][key]: section:20f96c9e-adbc-414a-856f-46f407132b57
sources[0][id]: 1
showSiteMenu: 0

**Comment by sebastian-lenz** [comment]
Hi @piotrpog, thanks for sharing this! I've published an update that should fix the issue. Also you may resolve the issue by checking the field settings and resaving them.
