### ISSUE TITLE
Type error - Argument 4 passed to typedlinkfield\models\InputLinkType::getInputHtml() must implement interface craft\base\ElementInterface, null given

### ISSUE THREAD

**Issue by starlifter-nz** [sebastian-lenz/craft-linkfield#90]
I keep coming across the following error:

```
TypeError
Argument 4 passed to typedlinkfield\models\InputLinkType::getInputHtml() must implement interface craft\base\ElementInterface, null given, called in /var/www/vendor/sebastianlenz/linkfield/src/fields/LinkField.php on line 226
```
What other information is useful in troubleshooting this?

**Comment by Mosnar** [comment]
@starlifter-nz Would suggest including your Craft version and Link Field version as well as other installed plugins

**Comment by starlifter-nz** [comment]
@Mosnar 

I am using the following CMS version and plugins:
```
    "aelvan/imager": "v2.3.1",
    "craftcms/cms": "3.4.2",
    "sebastianlenz/linkfield": "1.0.19",
    "vlucas/phpdotenv": "^3.4.0"
```

**Comment by sebastian-lenz** [comment]
Hm, okay, I can see the bug in theory, tracing back the called function, Crafts API actually might send a null value here. But it never happened before (at least I've never seen this case and it has never been reported).

@starlifter-nz Out of curiosity:
- When does the error trigger / What do you have to do to trigger the error?
- How ist the link field used? Is it on an entry or within a matrix field or something?

Nevertheless, I've adjusted the code so that it accepts a value of `null` here, please change the version requirement in your composer file to the following, run `composer update` and tell us if the error is gone:

```
"sebastianlenz/linkfield": "dev-master",
```

**Comment by starlifter-nz** [comment]
@sebastian-lenz The dev-master seems to be working for me now. Working like a charm.

It's hard to pinpoint the bug exactly. I would set up the fields, fill out the content in the entries and then update my templates and when I next refresh the control panel the error would happen.

It is used in a channel
![Screen Shot 2020-02-05 at 3 54 09 PM](https://user-images.githubusercontent.com/3903493/73806952-c7bdf800-482f-11ea-8843-d2b7ff49037a.png)

![Screen Shot 2020-02-05 at 3 53 17 PM](https://user-images.githubusercontent.com/3903493/73806902-afe67400-482f-11ea-8e41-c13fae227c4a.png)

**Comment by sebastian-lenz** [comment]
Okay, I've released a new version containing the fix.
